[defaults]
"pollutatnts" = [
    "SO2",
    "SO4--",
    "SO4 (H2SO4 aerosols) (SO4--)",
    "PM10",
    "PM2.5",
    "O3",
    "NO2",
    "CO",
    "NO",
    "OC",
    "EC",
    "C6H6",
    "EC in PM2.5",
    "OC in PM2.5",
    "EC in PM10",
    "OC in PM10",
    "NH4+ in PM2.5",
    "NO3- in PM2.5",
    "NH4+ in PM10",
    "NO3- in PM10",
    "HNO3",
]

[units]
"bq" = "Bq"
"fg.m-3" = "fg/m3"
"m-1" = "m-1"
"mg.l-1" = "mg/l"
"mg.m-3" = "mg/m3"
"mg.m-3.day" = "mg/m-3.day"
"mg.m-3.h" = "mg/m3.h"
"mgn.l-1" = "mg N/l"
"mgn.m-2.m-1" = "mg N/m2/m"
"mgs.l-1" = "mg S/l"
"mgs.m-1" = "mgS.m-1"
"mgs.m-2.m-1" = "mg S/m2.m"
"mm" = "mm"
"ng.l-1" = "ng/l"
"ng.m-2" = "ng/m2"
"ng.m-2.day-1" = "ng/m2/day"
"ng.m-3" = "ng/m3"
"phunits" = "pH units"
"particles.cm-3" = "particles.cm-3"
"pg.m-2.day-1" = "pg/m2/day"
"pg.m-3" = "pg/m3"
"ppbv" = "ppbv"
"ppmv" = "ppmv"
"pptv" = "pptv"
"us.cm-1" = "uS/cm"
"ueh.l-1" = "ue H/l"
"ug.l-1" = "µg/l"
"ug.m-2.day-1" = "ug/m2/day"
"ug.m-3" = "µg/m3"
"ug.m-3.day" = "ug/m3·day"
"ug.m-3.h" = "ug/m3·h"
"ugc.m-3" = "µg C/m3"
"ugn.m-3" = "µg N/m3"
"ugno2.m-3" = "ugNO2/m3"
"ugs.m-3" = "µg S/m3"
"ugso2.m-3" = "µg SO2/m3"
"nm" = "nm"


[pollutant]
1 = "SO2"
10 = "CO"
1012 = "Pb in PM2.5"
1013 = "Hg in PM2.5"
1014 = "Cd in PM2.5"
1015 = "Ni in PM2.5"
1016 = "Cr in PM2.5"
1017 = "Mn in PM2.5"
1018 = "As in PM2.5"
1129 = "BaP in PM2.5"
1045 = "NH4+ in PM2.5"
1046 = "NO3- in PM2.5"
1047 = "SO42- in PM2.5"
1048 = "Se in PM2.5"
1049 = "V in PM2.5"
1063 = "Zn in PM2.5"
1064 = "Co in PM2.5"
1065 = "Fe in PM2.5"
1073 = "Cu in PM2.5"
11 = "H2S"
7012 = "Pb"
7013 = "Hg"
7014 = "Cd"
1419 = "Dibenzo(ah)anthracene in PM2.5"
7015 = "Ni"
7016 = "Cr"
1610 = "Benzo(a)anthracene in PM2.5"
1617 = "Benzo(b)fluoranthene in PM2.5"
1626 = "Benzo(k)fluoranthene in PM2.5"
1629 = "Ca2+ in PM2.5"
1631 = "Cl- in PM2.5"
1655 = "Indeno-(1,2,3-cd)pyrene in PM2"
1657 = "K+ in PM2.5"
1659 = "Mg2+ in PM2.5"
1668 = "Na+  in PM2.5"
2017 = "Mn"
1759 = "Benzo(j)fluoranthene in PM2.5"
1771 = "EC in PM2.5"
1772 = "OC in PM2.5"
7018 = "As"
19 = "CS2"
20 = "C6H6"
7063 = "Zn"
64 = "Co"
65 = "Fe"
7073 = "Cu"
2076 = "pH"
21 = "C6H5-CH3"
22 = "C6H5-CH=CH2"
23 = "CH2=CH-CN"
7380 = "Benzo(b,j,k)fluoranthene"
24 = "CH2=CH-CH=CH2"
25 = "HCHO"
26 = "CHCl=CCl2"
455 = "C2Cl4"
2770 = "PO43-"
28 = "CH2Cl2"
7029 = "BaP"
3 = "SA"
30 = "PAH"
3012 = "Pb in TSP"
3013 = "Hg in TSP"
3014 = "Cd in TSP"
3015 = "Ni in TSP"
3016 = "Cr in TSP"
3017 = "Mn in TSP"
3018 = "As in TSP"
302 = "CFC-11"
303 = "CFC-113"
304 = "CFC-12"
3063 = "Zn in TSP"
307 = "HCFC-123"
3073 = "Cu in TSP"
308 = "HCFC-22"
309 = "1-methylnaphtalene"
31 = "VC"
310 = "1-methylphenanthrene"
311 = "Methyletylketone (MEK)"
312 = "Crotonaldehyde"
313 = "2-methylanthracene"
314 = "2-methylbenzaldehyde"
315 = "2-methylnaphtalene"
316 = "(CH3)2-CH-CH2-CH2-CH3"
317 = "2-methylphenanthrene"
318 = "Methacroleine"
319 = "Methylglyoxal"
32 = "THC (NM)"
320 = "Acroleine"
321 = "Methylvinylketone (MVK)"
322 = "3-methylbenzaldehyde"
323 = "3-methylpentane"
324 = "4-methylbenzaldehyde"
326 = "NOy"
33 = "T-VOC"
4330 = "PCB-105"
333 = "PCB-128"
4336 = "PCB-149"
4339 = "PCB-156"
34 = "PAN"
340 = "PCB-177"
4341 = "PCB-18"
344 = "PCB-26"
4347 = "PCB-31"
348 = "PCB-44"
35 = "NH3"
7351 = "Acenaphthene"
352 = "Acenaphtylene"
780 = "Aldrin"
36 = "N-DEP"
3631 = "Cl- in TSP"
7364 = "Anthanthrene"
3668 = "Na+  in TSP"
37 = "S-DEP"
372 = "Benzaldehyde"
373 = "Benzo(a)fluoranthene"
38 = "NO"
380 = "Benzo(b+j+k)fluoranthenes"
7381 = "Benzo(e)pyrene"
39 = "HCl"
7390 = "Biphenyl"
391 = "Black Carbon"
393 = "Butanales"
394 = "H3C-CH2-CH2-CH3"
395 = "Butenes"
4 = "SPM"
40 = "HF"
401 = "Carbon-tetrachloride"
4013 = "Hg0"
7406 = "Chrysene"
41 = "CH4"
412 = "k"
7415 = "Coronene"
416 = "Cyclo-hexane"
417 = "Cyklopenta(cd)pyrene"
418 = "Dibenzo(ac+ah)anthracenes"
763 = "Dibenzo(ah)anthracene"
420 = "Dibenzofuran"
421 = "Dibenzothiophene"
425 = "N2O"
426 = "Endrin"
427 = "Acetaldehyde"
428 = "C2H6"
429 = "Glyoxal"
430 = "H2C=CH2"
431 = "C6H5-C2H5"
432 = "HC=CH"
7435 = "Fluorene"
438 = "Halon 1211"
439 = "Halon 1301"
779 = "Heptachlor"
7407 = "Chrysene + Triphenylene"
441 = "C7H16"
442 = "n-Hexanal"
443 = "C6H14"
447 = "H3C-CH(CH3)2"
448 = "i-Heptane"
449 = "(CH3)3-C-CH2-CH-(CH3)2"
45 = "NH4"
450 = "H3C-CH2-CH(CH3)2"
451 = "CH2=CH-C(CH3)=CH2"
46 = "NO3"
463 = "Methyl-chloroform"
464 = "m,p-C6H4(CH3)2"
465 = "Naphtalene"
466 = "Neo-hexane"
467 = "Neo-pentane"
47 = "SO4 (H2SO4 aerosols) (SO4--)"
475 = "C8H18"
48 = "Se"
4813 = "Hg0 + Hg-reactive"
482 = "o-C6H4-(CH3)2"
485 = "Valeraldehyde"
486 = "H3C-(CH2)3-CH3"
487 = "Pentenes"
7488 = "Perylene"
49 = "V"
491 = "Acetophenone"
5 = "PM10"
50 = "HNO3"
5012 = "Pb in PM10"
5013 = "Hg in PM10"
5014 = "Cd in PM10"
5015 = "Ni in PM10"
5016 = "Cr in PM10"
5017 = "Mn in PM10"
5018 = "As in PM10"
502 = "Propanal"
5129 = "BaP in PM10"
503 = "H3C-CH2-CH3"
504 = "Acetone"
5045 = "NH4+ in PM10"
5046 = "NO3- in PM10"
5047 = "SO42-  in PM10"
5048 = "Se in PM10"
5049 = "V in PM10"
505 = "CH2=CH-CH3"
5063 = "Zn in PM10"
5064 = "Co in PM10"
5065 = "Fe in PM10"
5073 = "Cu in PM10"
508 = "Retene"
51 = "HC C2-C6(excl. AROM. & CHLH)"
517 = "sum-PCB"
52 = "HC > C6 (excl. AROM. & CHLH)"
520 = "SO2 + SO4--"
53 = "Aromatics (except C6H6)"
6380 = "Benzo(b,j,k)fluorantheneInPM1"
54 = "Chlorinated hydrocarbons"
5418 = "Dibenzo(ac+ah)anthracene in PM10"
5763 = "Dibenzo(ah)anthracene in PM10"
5480 = "Benzo(b,j)fluorantheneinPM10"
5610 = "Benzo(a)anthracene in PM10"
648 = "H+"
5617 = "Benzo(b)fluoranthene in PM10"
5626 = "Benzo(k)fluoranthene in PM10"
5629 = "Ca2+ in PM10"
5631 = "Cl- in PM10"
5655 = "Indeno-(1,2,3-cd)pyrene in PM"
5657 = "K+ in PM10"
5659 = "Mg2+ in PM10"
5668 = "Na+  in PM10"
5762 = "Benzo(j)fluoranthene in PM10"
5771 = "EC in PM10"
5772 = "OC in PM10"
6 = "BS"
6001 = "PM2.5"
6002 = "PM1"
6005 = "H2C=CH-CH2-CH3"
6006 = "trans-H3C-CH=CH-CH3"
6007 = "cis-H3C-CH=CH-CH3"
6008 = "H2C=CH-CH2-CH2-CH3"
6009 = "H3C-HC=CH-CH2-CH3"
601 = "3-methylphenantrene"
6011 = "1,2,4-C6H3(CH3)3"
6012 = "1,2,3-C6H3(CH3)3"
6013 = "1,3,5-C6H3(CH3)3"
602 = "9-methylphenantrene"
605 = "Al"
608 = "Anthracene"
611 = "Benzo(a)anthracene"
613 = "Benzo(a)fluorene"
618 = "Benzo(b)fluoranthene"
619 = "Benzo(b)fluorene"
62 = "Fluor (except HF)"
621 = "Benzo(ghi)fluoranthene"
624 = "Benzo(ghi)perylene"
627 = "Benzo(k)fluoranthene"
630 = "Ca++"
632 = "Cl-"
634 = "Dibenz(ac+ah)anthracenes"
635 = "Dibenz(ah)anthracene"
7636 = "Dibenzo(ae)pyrene"
7637 = "Dibenzo(ah)pyrene"
7639 = "Dibenzo(ai)pyrene"
7640 = "Dieldrin"
645 = "Fluoranthene"
7781 = "HCB"
652 = "Heptachlor Epoxide"
653 = "Hg-reactive"
656 = "Indeno-(1,2,3-cd)pyrene"
658 = "K+"
660 = "Mg++"
66 = "Back scattering"
661 = "Mo"
664 = "NH4+"
666 = "NO3-"
669 = "Na+"
67 = "HNO3+NO3"
672 = "PCB-101"
673 = "PCB-114"
676 = "PCB-118"
678 = "PCB-138"
679 = "PCB-141"
68 = "NH3+NH4"
682 = "PCB-153"
683 = "PCB-157"
684 = "PCB-167"
685 = "PCB-170"
688 = "PCB-180"
689 = "PCB-183"
69 = "Radioactivity"
690 = "PCB-187"
691 = "PCB-189"
692 = "PCB-194"
693 = "PCB-206"
694 = "PCB-209"
697 = "PCB-28"
698 = "PCB-33"
699 = "PCB-37"
7 = "O3"
700 = "PCB-47"
703 = "PCB-52"
704 = "PCB-60"
705 = "PCB-66"
706 = "PCB-74"
707 = "PCB-99"
708 = "PCB_122"
709 = "PCB_123"
71 = "CO2"
710 = "PCB_128"
711 = "PCB_138"
714 = "Phenanthrene"
717 = "Pyrene"
719 = "SO4--"
720 = "SO4-- corr"
723 = "TI"
728 = "Vanadium"
731 = "alpha-HCH"
733 = "beta-HCH"
7734 = "cis-CD"
736 = "cis-NO"
739 = "gamma-HCH"
744 = "o,p'-DDD"
745 = "o,p'-DDE"
746 = "o,p'-DDT"
7750 = "p,p'-DDD"
7751 = "p,p'-DDE"
7752 = "p,p'-DDT"
753 = "precip_amount"
754 = "precip_amount_off"
7755 = "trans-CD"
7757 = "trans-NO"
758 = "trans_NO"
762 = "Benzo(j)fluoranthene"
761 = "Benzo(j)fluorene"
771 = "EC"
772 = "OC"
78 = "C6H4-(CH3)2"
8 = "NO2"
80 = "p-C6H4(CH3)2"
81 = "m-C6H4-(CH3)2"
82 = "trans-H3C-HC=CH-CH2-CH3"
83 = "cis-H3C-HC=CH-CH2-CH3"
9 = "NOX as NO2"
5301 = "1-Methyl anthracene in PM10"
5364 = "Anthanthrene in PM10"
5381 = "Benzo(e)pyrene in PM10"
5406 = "Chrysene in PM10"
5415 = "Coronene in PM10"
5417 = "Cyclopenta(c,d)pyrene in PM10"
5488 = "Perylene in PM10"
5521 = "4.5-Methylene phenanthrene in PM10"
5622 = "5-Methyl Chrysene in PM10"
5523 = "9-Methyl anthracene in PM10"
5624 = "Benzo(b)naphtho(2,1-d)thiophene in PM10"
5725 = "Benzo(c)phenanthrene in PM10"
5526 = "Cholanthrene in PM10"
5627 = "Dibenzo(ac)anthracene in PM10"
5628 = "Dibenzo(al)pyrene in PM10"
5580 = "Benzo(b+j)fluoranthene in PM10"
5623 = "Benzo(ghi)perylene in PM10"
5733 = "Dibenzo(ah+ac)anthracene in PM10"
5636 = "Dibenzo(ae)pyrene in PM10"
4867 = "PFDA"
5637 = "Dibenzo(ah)pyrene in PM10"
5639 = "Dibenzo(ai)pyrene in PM10"
7301 = "1-Methyl anthracene"
7309 = "1-Methyl Naphthalene"
7310 = "1-Methyl phenanthrene"
7313 = "2-Methyl anthracene"
7315 = "2-Methyl Naphthalene"
7317 = "2-Methyl phenanthrene"
7352 = "Acenaphthylene"
7417 = "Cyclopenta(c,d)pyrene"
7418 = "Dibenzo(ah+ac)anthracene"
7465 = "Naphthalene"
7480 = "Benzo(b+j)fluoranthene"
7521 = "4.5-Methylene phenanthrene"
7522 = "5-Methyl Chrysene"
7523 = "9-Methyl anthracene"
7524 = "Benzo(b)naphtho(2,1-d)thiophene"
7525 = "Benzo(c)phenanthrene"
7526 = "Cholanthrene"
7527 = "Dibenzo(ac)anthracene"
7528 = "Dibenzo(al)pyrene"
374 = "C8H8O"
396 = "Methacroleine + Butanal"
434 = "C9H12"
453 = "C6H4Cl2"
454 = "C9H20"
456 = "Tetrachloromethane (air)"
457 = "Chlorobenzene (air)"
458 = "1,1,2-trichloroethane (air)"
459 = "1,1-dichloroethane (air)"
460 = "1,2-dichloroethylene (air)"
461 = "1,2-dichloroethane (air)"
462 = "1,1,1-trichloroethane (air)"
506 = "CH2=CH-CH3 + H3C-CH2-CH2-CH3"
5060 = "Sn in PM10"
507 = "H3C-(CH2)3-CH3 + H3C-CH2-CH(CH3)2"
509 = "Acetone + Acrolein"
5606 = "Anthracene in PM10 (aerosol)"
5643 = "Fluoranthene in PM10 (aerosol)"
5712 = "Phenanthrene in PM10 (aerosol)"
5715 = "Pyrene in PM10 (aerosol)"
6016 = "C6H12"
6400 = "VPM10"
6401 = "NVPM10"
6410 = "VPM2.5"
6411 = "NVPM2.5"
6420 = "VPM1"
6421 = "NVPM1"
4861 = "PFBA"
4862 = "PFPeA"
4863 = "PFHxA"
4864 = "PFHpA"
4865 = "PFOA"
4866 = "PFNA"
4868 = "PFUnDA"
4871 = "PFBS"
4872 = "PFHxS"
4873 = "PFOSA"
4874 = "6:2-FTS"
4875 = "PFOS"
4876 = "PFDS"
7821 = "TCDD"
7822 = "CDD1N"
7823 = "CDD4X"
7824 = "CDD6X"
7825 = "CDD9X"
7826 = "CDD6P"
7827 = "CDDO"
7841 = "CDF2T"
7842 = "CDFDN"
7843 = "CDF2N"
7844 = "CDFDX"
7845 = "CDF6X"
7846 = "CDF9X"
7847 = "CDF4X"
7848 = "CDF6P"
7849 = "CDF9P"
7850 = "CDFO"
7851 = "CDFX1"
7852 = "CDFP2"
7901 = "BDE47"
7902 = "BDE85"
7903 = "BDE99"
7904 = "BDE100"
7905 = "BDE153"
7906 = "BDE154"
7907 = "BDE209"
7908 = "SCCP"
7909 = "MCCP"
7910 = "HBCD"
4911 = "HBB"
4912 = "PBT"
4913 = "PBEB"
4914 = "α-DBE-DBCH"
4915 = "β-DBE-DBCH"
4916 = "BEH-TEBP"
4917 = "BTBPT"
4918 = "EH-TBB"
4919 = "Syn-DP"
4920 = "Anti-DP"
4921 = "DBDPE"
4922 = "TBP"
7773 = "alpha-Endosulfan"
7774 = "beta-Endosulfan"
7775 = "Endosulfan sulfate"
7776 = "DCMU"
7777 = "Atrazine"
778 = "Isoproturon"
2771 = "TP"
667 = "Kj-N"
6017 = "C6H12O2"
6003 = "UFPs"
6382 = "Benzo(k+j)fluoranthene"
5382 = "Benzo(k+j)fluoranthene in PM10"
view = "NT"
